---
title: "PS 2"
output: html_document
date: "2024-04-19"
---
(Inspired by Diego and Colleagues)

(Due to computational limits, we only do 1000 draws. So the graph is wonky)

Set up p and t values
```{r}
library(MASS)

#U^2 = 0

beta_tsls_0 <- matrix(0, nrow = 10000, ncol = 1)

t_value_0 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_t_0 <- matrix(0, nrow = 10000, ncol = 1)

AR_0 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_AR_0 <- matrix(0, nrow = 10000, ncol = 1)

for(draws in 1:1000){
  Sigma_d <- matrix(c(1, 0.99, 0.99, 1), nrow=2, ncol = 2)
  
  errors <- mvrnorm(n = 500, mu = c(0, 0), Sigma = Sigma_d)
  
  beta_ols <- cor(errors[,1], errors[,2])/sd(errors[,2])
  
  z <- matrix(1, nrow = 500, ncol = 1)
  
  u <- sqrt(0)
  
  pi <- u/sum(z)^(1/2)
  
  y <- matrix(0, nrow = 500, ncol = 1)
  
  x <- matrix(0, nrow = 500, ncol = 1)
  
  for(i in 1:length(errors[,1])){
    x[i] <- pi*z[i] + errors[i,2]   
  }
  
  for(i in 1:length(errors[,1])){
    y[i] <- errors[i,1]   
  }
  
  beta_tsls <- solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x)%*%t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%y #2SLS
  
  beta_tsls_0[draws] <- beta_tsls 
  
  u <- y - x%*%beta_tsls_0[draws]
  
  sigma <- as.vector((t(u)%*%u)/length(y))
  
  v_hom <- length(y)*(sigma*solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x))
  
  t_value <- sqrt(length(y)-1)%*%beta_tsls_0[draws]%*%solve(sqrt(v_hom))
  
  t_value_0[draws] <- t_value
  
  Pvalue <- pnorm(t_value, lower.tail = FALSE)
  
  pvalue_t_0[draws] <- Pvalue
  
  Y_bar <- matrix(c(y, x), nrow = 500, ncol = 2)
  b0 <- matrix(c(1, 0), nrow = 2, ncol = 1)
  Mz <- diag(500) -  z%*%solve(t(z)%*%z)%*%t(z)
  
  num <- (t(z)%*%z)^(-1/2)*t(z)%*%Y_bar%*%b0 
  
  omega <- t(Y_bar)%*%Mz%*%Y_bar/(length(x)-1)
  den <- sqrt(t(b0)%*%omega%*%b0)
  
  S <- num/den
  
  AR <- S*S
  
  Pvalue <- pchisq(AR, 1)
  
  AR_0[draws] <- AR
  
  pvalue_AR_0[draws] <- Pvalue
}

Q <- quantile(beta_tsls_0, probs=c(.05, .95), na.rm = FALSE)

beta_tsls_0 <- subset(beta_tsls_0, beta_tsls_0 > Q[1] & beta_tsls_0 < Q[2])


plot(density(beta_tsls_0), main = "Density of 2SLS estimator")
```

```{r}
Q <- quantile(t_value_0, probs=c(.05, .95), na.rm = FALSE)

t_value_0 <- subset(t_value_0, t_value_0 > Q[1] & t_value_0 < Q[2])

plot(density(t_value_0), main = "Density plot of t-values")
```


```{r}
Q <- quantile(AR_0, probs=c(.05, .95), na.rm = FALSE)

AR_0 <- subset(AR_0, AR_0 > Q[1] & AR_0 < Q[2])

plot(density(AR_0), "Anderson Rubin Statistic")
```


```{r}
#U^2 = 0.25

beta_tsls_0.25 <- matrix(0, nrow = 10000, ncol = 1)

t_value_0.25 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_t_0.25 <- matrix(0, nrow = 10000, ncol = 1)

AR_0.25 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_AR_0.25 <- matrix(0, nrow = 10000, ncol = 1)

for(draws in 1:1000){
  Sigma_d <- matrix(c(1, 0.99, 0.99, 1), nrow=2, ncol = 2)
  
  errors <- mvrnorm(n = 500, mu = c(0, 0), Sigma = Sigma_d)
  
  beta_ols <- cor(errors[,1], errors[,2])/sd(errors[,2])
  
  z <- matrix(1, nrow = 500, ncol = 1)
  
  u <- sqrt(0.25)
  
  pi <- u/sum(z)^(1/2)
  
  y <- matrix(0, nrow = 500, ncol = 1)
  
  x <- matrix(0, nrow = 500, ncol = 1)
  
  for(i in 1:length(errors[,1])){
    x[i] <- pi*z[i] + errors[i,2]   
  }
  
  for(i in 1:length(errors[,1])){
    y[i] <- errors[i,1]   
  }
  
  
  
  beta_tsls <- solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x)%*%t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%y #2SLS
  
  beta_tsls_0.25[draws] <- beta_tsls 
  
  u <- y - x%*%beta_tsls_0.25[draws]
  
  sigma <- as.vector((t(u)%*%u)/length(y))
  
  v_hom <- length(y)*(sigma*solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x))
  
  t_value <- sqrt(length(y)-1)%*%beta_tsls_0.25[draws]%*%solve(sqrt(v_hom))
  
  t_value_0.25[draws] <- t_value
  
  Pvalue <- pnorm(t_value, lower.tail = FALSE)
  
  pvalue_t_0.25[draws] <- Pvalue
  
  Y_bar <- matrix(c(y, x), nrow = 500, ncol = 2)
  b0 <- matrix(c(1, 0), nrow = 2, ncol = 1)
  Mz <- diag(500) -  z%*%solve(t(z)%*%z)%*%t(z)
  
  num <- (t(z)%*%z)^(-1/2)*t(z)%*%Y_bar%*%b0 
  
  omega <- t(Y_bar)%*%Mz%*%Y_bar/(length(x)-1)
  den <- sqrt(t(b0)%*%omega%*%b0)
  
  S <- num/den
  
  AR <- S*S
  
  Pvalue <- pchisq(AR, 1)
  
  AR_0.25[draws] <- AR
  
  pvalue_AR_0.25[draws] <- Pvalue
}

Q <- quantile(beta_tsls_0.25, probs=c(.05, .95), na.rm = FALSE)

beta_tsls_0.25 <- subset(beta_tsls_0.25, beta_tsls_0.25 > Q[1] & beta_tsls_0.25 < Q[2])


plot(density(beta_tsls_0.25))

Q <- quantile(t_value_0.25, probs=c(.05, .95), na.rm = FALSE)

t_value_0.25 <- subset(t_value_0.25, t_value_0.25 > Q[1] & t_value_0.25 < Q[2])

plot(density(t_value_0.25))

Q <- quantile(AR_0.25, probs=c(.05, .95), na.rm = FALSE)

AR_0.25 <- subset(AR_0.25, AR_0.25 > Q[1] & AR_0.25 < Q[2])

plot(density(AR_0.25))


#U^2 = 10

beta_tsls_10 <- matrix(0, nrow = 10000, ncol = 1)

t_value_10 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_t_10 <- matrix(0, nrow = 10000, ncol = 1)

AR_10 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_AR_10 <- matrix(0, nrow = 10000, ncol = 1)

for(draws in 1:1000){
  Sigma_d <- matrix(c(1, 0.99, 0.99, 1), nrow=2, ncol = 2)
  
  errors <- mvrnorm(n = 500, mu = c(0, 0), Sigma = Sigma_d)
  
  beta_ols <- cor(errors[,1], errors[,2])/sd(errors[,2])
  
  z <- matrix(1, nrow = 500, ncol = 1)
  
  u <- sqrt(10)
  
  pi <- u/sum(z)^(1/2)
  
  y <- matrix(0, nrow = 500, ncol = 1)
  
  x <- matrix(0, nrow = 500, ncol = 1)
  
  for(i in 1:length(errors[,1])){
    x[i] <- pi*z[i] + errors[i,2]   
  }
  
  for(i in 1:length(errors[,1])){
    y[i] <- errors[i,1]   
  }
  
  
  
  beta_tsls <- solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x)%*%t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%y #2SLS
  
  beta_tsls_10[draws] <- beta_tsls 
  
  u <- y - x%*%beta_tsls_10[draws]
  
  sigma <- as.vector((t(u)%*%u)/length(y))
  
  v_hom <- length(y)*(sigma*solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x))
  
  t_value <- sqrt(length(y)-1)%*%beta_tsls_10[draws]%*%solve(sqrt(v_hom))
  
  t_value_10[draws] <- t_value
  
  Pvalue <- pnorm(t_value, lower.tail = FALSE)
  
  pvalue_t_10[draws] <- Pvalue
  
  Y_bar <- matrix(c(y, x), nrow = 500, ncol = 2)
  b0 <- matrix(c(1, 0), nrow = 2, ncol = 1)
  Mz <- diag(500) -  z%*%solve(t(z)%*%z)%*%t(z)
  
  num <- (t(z)%*%z)^(-1/2)*t(z)%*%Y_bar%*%b0 
  
  omega <- t(Y_bar)%*%Mz%*%Y_bar/(length(x)-1)
  den <- sqrt(t(b0)%*%omega%*%b0)
  
  S <- num/den
  
  AR <- S*S
  
  Pvalue <- pchisq(AR, 1)
  
  AR_10[draws] <- AR
  
  pvalue_AR_10[draws] <- Pvalue
}

Q <- quantile(beta_tsls_10, probs=c(.05, .95), na.rm = FALSE)

beta_tsls_10 <- subset(beta_tsls_10, beta_tsls_10 > Q[1] & beta_tsls_10 < Q[2])


plot(density(beta_tsls_10))

Q <- quantile(t_value_10, probs=c(.05, .95), na.rm = FALSE)

t_value_10 <- subset(t_value_10, t_value_10 > Q[1] & t_value_10 < Q[2])

plot(density(t_value_10))

Q <- quantile(AR_10, probs=c(.05, .95), na.rm = FALSE)

AR_10 <- subset(AR_10, AR_10 > Q[1] & AR_10 < Q[2])

plot(density(AR_10))


#U^2 = 100

beta_tsls_100 <- matrix(0, nrow = 10000, ncol = 1)

t_value_100 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_t_100 <- matrix(0, nrow = 10000, ncol = 1)

AR_100 <- matrix(0, nrow = 10000, ncol = 1)

pvalue_AR_100 <- matrix(0, nrow = 10000, ncol = 1)

for(draws in 1:1000){
  Sigma_d <- matrix(c(1, 0.99, 0.99, 1), nrow=2, ncol = 2)
  
  errors <- mvrnorm(n = 500, mu = c(0, 0), Sigma = Sigma_d)
  
  beta_ols <- cor(errors[,1], errors[,2])/sd(errors[,2])
  
  z <- matrix(1, nrow = 500, ncol = 1)
  
  u <- sqrt(100)
  
  pi <- u/sum(z)^(1/2)
  
  y <- matrix(0, nrow = 500, ncol = 1)
  
  x <- matrix(0, nrow = 500, ncol = 1)
  
  for(i in 1:length(errors[,1])){
    x[i] <- pi*z[i] + errors[i,2]   
  }
  
  for(i in 1:length(errors[,1])){
    y[i] <- errors[i,1]   
  }
  
  
  
  beta_tsls <- solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x)%*%t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%y #2SLS
  
  beta_tsls_100[draws] <- beta_tsls 
  
  u <- y - x%*%beta_tsls_100[draws]
  
  sigma <- as.vector((t(u)%*%u)/length(y))
  
  v_hom <- length(y)*(sigma*solve(t(x)%*%z%*%solve(t(z)%*%z)%*%t(z)%*%x))
  
  t_value <- sqrt(length(y)-1)%*%beta_tsls_100[draws]%*%solve(sqrt(v_hom))
  
  t_value_100[draws] <- t_value
  
  Pvalue <- pnorm(t_value, lower.tail = FALSE)
  
  pvalue_t_100[draws] <- Pvalue
  
  Y_bar <- matrix(c(y, x), nrow = 500, ncol = 2)
  b0 <- matrix(c(1, 0), nrow = 2, ncol = 1)
  Mz <- diag(500) -  z%*%solve(t(z)%*%z)%*%t(z)
  
  num <- (t(z)%*%z)^(-1/2)*t(z)%*%Y_bar%*%b0 
  
  omega <- t(Y_bar)%*%Mz%*%Y_bar/(length(x)-1)
  den <- sqrt(t(b0)%*%omega%*%b0)
  
  S <- num/den
  
  AR <- S*S
  
  Pvalue <- pchisq(AR, 1, lower.tail = FALSE)
  
  AR_100[draws] <- AR
  
  pvalue_AR_100[draws] <- Pvalue
}

Q <- quantile(beta_tsls_100, probs=c(.05, .95), na.rm = FALSE)

beta_tsls_100 <- subset(beta_tsls_100, beta_tsls_100 > Q[1] & beta_tsls_100 < Q[2])


plot(density(beta_tsls_100))

Q <- quantile(t_value_100, probs=c(.05, .95), na.rm = FALSE)

t_value_100 <- subset(t_value_100, t_value_100 > Q[1] & t_value_100 < Q[2])

plot(density(t_value_100))

Q <- quantile(AR_100, probs=c(.05, .95), na.rm = FALSE)

AR_100 <- subset(AR_100, AR_100 > Q[1] & AR_100 < Q[2])

plot(density(AR_100))



#Comparison of probabilities



length(subset(pvalue_t_0,pvalue_t_0 < 0.05))/length(pvalue_t_0)

length(subset(pvalue_t_0.25,pvalue_t_0.25 < 0.05))/length(pvalue_t_0.25)

length(subset(pvalue_t_10,pvalue_t_10 < 0.05))/length(pvalue_t_10)

length(subset(pvalue_t_100,pvalue_t_100 < 0.05))/length(pvalue_t_100)


length(subset(pvalue_AR_0,pvalue_AR_0 < 0.05))/length(pvalue_AR_0)

length(subset(pvalue_AR_0.25,pvalue_AR_0.25 < 0.05))/length(pvalue_AR_0.25)

length(subset(pvalue_AR_10,pvalue_AR_10 < 0.05))/length(pvalue_AR_10)

length(subset(pvalue_AR_100,pvalue_AR_100 < 0.05))/length(pvalue_AR_100)


pchisq(0.95, 1)


#Plot for question e

dens_0 <- density(beta_tsls_0)
dens_0.25 <- density(beta_tsls_0.25)
dens_10 <- density(beta_tsls_10)
dens_100 <- density(beta_tsls_100)

plot(dens_0, main = "2SLS Estimator", xlab = "Value", ylab = "Probability Density", xlim = c(-2, 4), ylim = c(0, 4.5),lwd=2)
lines(dens_0.25,lty=3)
lines(dens_10, lty=1 )
lines(dens_100, lty=4)

legend("topright", 
       legend = c(expression(mu^2/k == 0), 
                  expression(mu^2/k == 0.25), 
                  expression(mu^2/k == 10), 
                  expression(mu^2/k == 100)), 
       lty = c(1, 3, 1, 4), 
       lwd= c(2,1,1,1),
       cex = 0.8)

#Plot 1 for question g

dens_0 <- density(t_value_0)
dens_0.25 <- density(t_value_0.25)
dens_10 <- density(t_value_10)
dens_100 <- density(t_value_100)

plot(dens_0, main = "t value", xlab = "Value", ylab = "Probability Density", xlim = c(-2, 4), ylim = c(0, 0.8),lwd=2)
lines(dens_0.25,lty=3)
lines(dens_10, lty=1 )
lines(dens_100, lty=4)

legend("topright", 
       legend = c(expression(mu^2/k == 0), 
                  expression(mu^2/k == 0.25), 
                  expression(mu^2/k == 10), 
                  expression(mu^2/k == 100)), 
       lty = c(1, 3, 1, 4), 
       lwd= c(2,1,1,1),
       cex = 0.8)

#Plot 2 for question g

dens_0 <- density(AR_0)
dens_0.25 <- density(AR_0.25)
dens_10 <- density(AR_10)
dens_100 <- density(AR_100)

plot(dens_0, main = "AR Statistic", xlab = "Value", ylab = "Probability Density", xlim = c(-2, 4), ylim = c(0, 1.2),lwd=2)
lines(dens_0.25,lty=3)
lines(dens_10, lty=1 )
lines(dens_100, lty=4)

legend("topright", 
       legend = c(expression(mu^2/k == 0), 
                  expression(mu^2/k == 0.25), 
                  expression(mu^2/k == 10), 
                  expression(mu^2/k == 100)), 
       lty = c(1, 3, 1, 4), 
       lwd= c(2,1,1,1),
       cex = 0.8)

#Comparison of rejection probabilities

t_value <- c(length(subset(pvalue_t_0,pvalue_t_0 < 0.05))/length(pvalue_t_0),
             length(subset(pvalue_t_0.25,pvalue_t_0.25 < 0.05))/length(pvalue_t_0.25),
             length(subset(pvalue_t_10,pvalue_t_10 < 0.05))/length(pvalue_t_10),
             length(subset(pvalue_t_100,pvalue_t_100 < 0.05))/length(pvalue_t_100))


AR_statistic <- c(length(subset(pvalue_AR_0,pvalue_AR_0 < 0.05))/length(pvalue_AR_0),
                  length(subset(pvalue_AR_0.25,pvalue_AR_0.25 < 0.05))/length(pvalue_AR_0.25),
                  length(subset(pvalue_AR_10,pvalue_AR_10 < 0.05))/length(pvalue_AR_10),
                  length(subset(pvalue_AR_100,pvalue_AR_100 < 0.05))/length(pvalue_AR_100))


muoverk <- c(0, 0.25, 10, 100)

table_g <- cbind(data.frame(muoverk), data.frame(t_value), data.frame(AR_statistic))

library(stargazer)

stargazer(table_g, summary = TRUE)
```
